apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-mongodb
spec:
  selector:
    app: mongo
  ports:
    - name: mongoport
      port: 27017

  type: ClusterIP
