apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
      nodePort: 30011
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-position-traker
spec:
  selector:
    app: position-traker
  ports:
    - name: http
      port: 8080
      nodePort: 38080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp
spec:
  selector:
    myLablelName: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort
