apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  #minReadySeconds: 15
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template: #template for pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: k8s-fleetman-queue
          image: richardchesterwood/k8s-fleetman-queue:release1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  #minReadySeconds: 15
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template: #template for pods
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
        - name: k8s-fleetman-position
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  #minReadySeconds: 15
  selector:
    matchLabels:
      app: position-tracker
  replicas: 1
  template: #template for pods
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: k8s-fleetman-position-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:release1
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  #minReadySeconds: 15
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template: #template for pods
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: k8s-fleetman-gateway
          image: richardchesterwood/k8s-fleetman-api-gateway:release1
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  #minReadySeconds: 15
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: #template for pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: k8s-fleetman-webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release1
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
